import unknownLogo from 'url:@/ui/assets/unknown.svg';

export const CHAIN_NAMESPACES = {
  EVM: 'eip155',
  SOLANA: 'solana',
} as const;

export type ChainNamespace =
  (typeof CHAIN_NAMESPACES)[keyof typeof CHAIN_NAMESPACES];

export type ChainRegistry = {
  caip: string | null;
  namespace: ChainNamespace;
  chain_identifier: number | null;
  name: string;
  native_coin_id: string | null;
  image: string;
  gecko_id: string | null;
};

export const CHAIN_REGISTRY: ChainRegistry[] = [
  {
    caip: 'eip155:48900',
    namespace: 'eip155',
    chain_identifier: 48900,
    name: 'Zircuit Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zircuit.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:57073',
    namespace: 'eip155',
    chain_identifier: 57073,
    name: 'Ink',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/57073/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:1100',
    namespace: 'eip155',
    chain_identifier: 1100,
    name: 'Dymension',
    native_coin_id: 'DYM',
    image: 'https://icons.llamao.fi/icons/chains/rsz_dymension.jpg',
    gecko_id: 'dymension',
  },
  {
    caip: 'eip155:420420418',
    namespace: 'eip155',
    chain_identifier: 420420418,
    name: 'Kusama',
    native_coin_id: 'KSM',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kusama.jpg',
    gecko_id: 'kusama',
  },
  {
    caip: 'eip155:2152',
    namespace: 'eip155',
    chain_identifier: 2152,
    name: 'Findora Mainnet',
    native_coin_id: 'FRA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_findora.jpg',
    gecko_id: 'findora',
  },
  {
    caip: 'eip155:96',
    namespace: 'eip155',
    chain_identifier: 96,
    name: 'KUB Mainnet',
    native_coin_id: 'KUB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bitkub.jpg',
    gecko_id: 'bitkub-coin',
  },
  {
    caip: 'eip155:50104',
    namespace: 'eip155',
    chain_identifier: 50104,
    name: 'Sophon',
    native_coin_id: 'SOPH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sophon.jpg',
    gecko_id: 'sophon',
  },
  {
    caip: 'eip155:1975',
    namespace: 'eip155',
    chain_identifier: 1975,
    name: 'ONUS Chain Mainnet',
    native_coin_id: 'ONUS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_onus.jpg',
    gecko_id: 'onus',
  },
  {
    caip: 'eip155:3693',
    namespace: 'eip155',
    chain_identifier: 3693,
    name: 'Empire Network',
    native_coin_id: 'EMPIRE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/118/small/empire.jpeg?1706606582',
    gecko_id: 'empire',
  },
  {
    caip: 'eip155:98866',
    namespace: 'eip155',
    chain_identifier: 98866,
    name: 'Plume Mainnet',
    native_coin_id: 'PLUME',
    image: 'https://icons.llamao.fi/icons/chains/rsz_plume.jpg',
    gecko_id: 'plume',
  },
  {
    caip: 'eip155:2109',
    namespace: 'eip155',
    chain_identifier: 2109,
    name: 'Exosama Network',
    native_coin_id: 'SAMA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/111/small/exosama_%282%29.png?1706606472',
    gecko_id: 'exosama',
  },
  {
    caip: 'eip155:9745',
    namespace: 'eip155',
    chain_identifier: 9745,
    name: 'Plasma Mainnet',
    native_coin_id: 'XPL',
    image: 'https://icons.llamao.fi/icons/chains/rsz_plasma.jpg',
    gecko_id: 'plasma',
  },
  {
    caip: 'eip155:6661',
    namespace: 'eip155',
    chain_identifier: 6661,
    name: 'Cybria Mainnet',
    native_coin_id: 'CYBA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/194/small/cybria.jpeg?1709690260',
    gecko_id: 'cybria',
  },
  {
    caip: 'eip155:10241024',
    namespace: 'eip155',
    chain_identifier: 10241024,
    name: 'AlienX Mainnet',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/277/small/alienx.png?1719305544',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:5165',
    namespace: 'eip155',
    chain_identifier: 5165,
    name: 'Bahamut',
    native_coin_id: 'FTN',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/256/small/bahamut.jpeg?1715338015',
    gecko_id: 'bahamut',
  },
  {
    caip: 'eip155:311',
    namespace: 'eip155',
    chain_identifier: 311,
    name: 'Omax Mainnet',
    native_coin_id: 'OMAX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_omax.jpg',
    gecko_id: 'omax',
  },
  {
    caip: 'eip155:2415',
    namespace: 'eip155',
    chain_identifier: 2415,
    name: 'XODEX',
    native_coin_id: 'XODEX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/158/small/xodex.jpeg?1706606643',
    gecko_id: 'xodex',
  },
  {
    caip: 'eip155:6322',
    namespace: 'eip155',
    chain_identifier: 6322,
    name: 'Aura Mainnet',
    native_coin_id: 'AURA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/145/small/aura_network.jpeg?1706606479',
    gecko_id: 'aura-network',
  },
  {
    caip: 'eip155:595',
    namespace: 'eip155',
    chain_identifier: 595,
    name: 'Acala Mandala Testnet TC9',
    native_coin_id: 'mACA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/73/small/Acala.jpeg?1706606499',
    gecko_id: 'acala',
  },
  {
    caip: 'eip155:16661',
    namespace: 'eip155',
    chain_identifier: 16661,
    name: '0G Mainnet',
    native_coin_id: '0G',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kasplex.jpg',
    gecko_id: 'zero-gravity',
  },
  {
    caip: 'eip155:40',
    namespace: 'eip155',
    chain_identifier: 40,
    name: 'Telos EVM Mainnet',
    native_coin_id: 'TLOS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_telos.jpg',
    gecko_id: 'telos',
  },
  {
    caip: 'eip155:416',
    namespace: 'eip155',
    chain_identifier: 416,
    name: 'SX Network Mainnet',
    native_coin_id: 'SX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sx.jpg',
    gecko_id: 'sx-network',
  },
  {
    caip: 'eip155:53935',
    namespace: 'eip155',
    chain_identifier: 53935,
    name: 'DFK Chain',
    native_coin_id: 'JEWEL',
    image: 'https://icons.llamao.fi/icons/chains/rsz_dfk.jpg',
    gecko_id: 'defi-kingdoms',
  },
  {
    caip: 'eip155:81224',
    namespace: 'eip155',
    chain_identifier: 81224,
    name: 'Codex',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32253/small/codex.png?1756784576',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:2342',
    namespace: 'eip155',
    chain_identifier: 2342,
    name: 'Omnia Chain',
    native_coin_id: 'OMNIA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/263/small/OmniaVerse.png?1716209921',
    gecko_id: 'omnia',
  },
  {
    caip: 'eip155:1135',
    namespace: 'eip155',
    chain_identifier: 1135,
    name: 'Lisk',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_lisk.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:6969',
    namespace: 'eip155',
    chain_identifier: 6969,
    name: 'Tomb Chain Mainnet',
    native_coin_id: 'TOMB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_tombchain.jpg',
    gecko_id: 'tombchain',
  },
  {
    caip: 'eip155:820',
    namespace: 'eip155',
    chain_identifier: 820,
    name: 'Callisto Mainnet',
    native_coin_id: 'CLO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_callisto.jpg',
    gecko_id: 'callisto',
  },
  {
    caip: 'eip155:530',
    namespace: 'eip155',
    chain_identifier: 530,
    name: 'Pundi AIFX Omnilayer',
    native_coin_id: 'PUNDAI',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/106/small/functionx.jpeg?1706606559',
    gecko_id: 'function-x',
  },
  {
    caip: 'eip155:2611',
    namespace: 'eip155',
    chain_identifier: 2611,
    name: 'Redlight Chain Mainnet',
    native_coin_id: 'REDLC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/104/small/redlight.jpg?1706606562',
    gecko_id: 'redlight-chain',
  },
  {
    caip: 'eip155:24',
    namespace: 'eip155',
    chain_identifier: 24,
    name: 'KardiaChain Mainnet',
    native_coin_id: 'KAI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kardia.jpg',
    gecko_id: 'kardiachain',
  },
  {
    caip: 'eip155:245022934',
    namespace: 'eip155',
    chain_identifier: 245022934,
    name: 'Neon EVM Mainnet',
    native_coin_id: 'NEON',
    image: 'https://icons.llamao.fi/icons/chains/rsz_neon.jpg',
    gecko_id: 'neon',
  },
  {
    caip: 'eip155:16507',
    namespace: 'eip155',
    chain_identifier: 16507,
    name: 'Genesys Mainnet',
    native_coin_id: 'GSYS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_genesys.jpg',
    gecko_id: 'genesys',
  },
  {
    caip: 'eip155:66',
    namespace: 'eip155',
    chain_identifier: 66,
    name: 'OKXChain Mainnet',
    native_coin_id: 'OKT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_okexchain.jpg',
    gecko_id: 'oec-token',
  },
  {
    caip: 'eip155:777777',
    namespace: 'eip155',
    chain_identifier: 777777,
    name: 'Winr Protocol Mainnet',
    native_coin_id: 'WINR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_winr.jpg',
    gecko_id: 'winr-protocol',
  },
  {
    caip: 'eip155:314',
    namespace: 'eip155',
    chain_identifier: 314,
    name: 'Filecoin - Mainnet',
    native_coin_id: 'FIL',
    image: 'https://icons.llamao.fi/icons/chains/rsz_filecoin.jpg',
    gecko_id: 'filecoin',
  },
  {
    caip: 'eip155:2222',
    namespace: 'eip155',
    chain_identifier: 2222,
    name: 'Kava',
    native_coin_id: 'KAVA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kava.jpg',
    gecko_id: 'kava',
  },
  {
    caip: 'eip155:60',
    namespace: 'eip155',
    chain_identifier: 60,
    name: 'GoChain',
    native_coin_id: 'GO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_gochain.jpg',
    gecko_id: 'gochain',
  },
  {
    caip: 'eip155:1612',
    namespace: 'eip155',
    chain_identifier: 1612,
    name: 'OpenLedger Mainnet',
    native_coin_id: 'OPEN',
    image:
      'https://assets.coingecko.com/coins/images/67482/standard/open.png?1756547643',
    gecko_id: 'openledger',
  },
  {
    caip: 'eip155:58',
    namespace: 'eip155',
    chain_identifier: 58,
    name: 'Ontology Mainnet',
    native_coin_id: 'ONG',
    image: 'https://icons.llamao.fi/icons/chains/rsz_ontologyevm.jpg',
    gecko_id: 'ong',
  },
  {
    caip: 'eip155:2039',
    namespace: 'eip155',
    chain_identifier: 2039,
    name: 'Aleph Zero',
    native_coin_id: 'TZERO',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/171/small/aleph.jpeg?1706606823',
    gecko_id: 'aleph-zero',
  },
  {
    caip: 'eip155:999',
    namespace: 'eip155',
    chain_identifier: 999,
    name: 'HyperEVM Mainnet',
    native_coin_id: 'HYPE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22208/small/hyperliquid.jpg?1740125774',
    gecko_id: 'hyperliquid',
  },
  {
    caip: 'eip155:151',
    namespace: 'eip155',
    chain_identifier: 151,
    name: 'Redbelly Network Mainnet',
    native_coin_id: 'RBNT',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22212/small/redbelly.jpg?1741146062',
    gecko_id: 'redbelly-network',
  },
  {
    caip: 'eip155:7000',
    namespace: 'eip155',
    chain_identifier: 7000,
    name: 'ZetaChain Mainnet',
    native_coin_id: 'ZETA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zetachain.jpg',
    gecko_id: 'zetachain',
  },
  {
    caip: 'eip155:37',
    namespace: 'eip155',
    chain_identifier: 37,
    name: 'Xpla Mainnet',
    native_coin_id: 'XPLA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/175/small/xpla.jpeg?1707990587',
    gecko_id: 'xpla',
  },
  {
    caip: 'eip155:686',
    namespace: 'eip155',
    chain_identifier: 686,
    name: 'Karura Network',
    native_coin_id: 'KAR',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/79/small/karura.jpeg?1706606510',
    gecko_id: 'karura',
  },
  {
    caip: 'eip155:6278',
    namespace: 'eip155',
    chain_identifier: 6278,
    name: 'Rails',
    native_coin_id: 'STEAMX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/183/small/railsnetwork.jpeg?1708321107',
    gecko_id: 'rails-network',
  },
  {
    caip: 'eip155:1818',
    namespace: 'eip155',
    chain_identifier: 1818,
    name: 'Cube Chain Mainnet',
    native_coin_id: 'CUBE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_cube.jpg',
    gecko_id: 'cube-network',
  },
  {
    caip: 'eip155:3068',
    namespace: 'eip155',
    chain_identifier: 3068,
    name: 'Bifrost Mainnet',
    native_coin_id: 'BFC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/240/small/bifrost.png?1713513431',
    gecko_id: 'bifrost-network',
  },
  {
    caip: 'eip155:1088',
    namespace: 'eip155',
    chain_identifier: 1088,
    name: 'Metis Andromeda Mainnet',
    native_coin_id: 'METIS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_metis.jpg',
    gecko_id: 'metis-token',
  },
  {
    caip: 'eip155:1110',
    namespace: 'eip155',
    chain_identifier: 1110,
    name: 'GRX Chain',
    native_coin_id: null,
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32276/small/grx.jpg?1767665852',
    gecko_id: 'grx-chain',
  },
  {
    caip: 'eip155:9',
    namespace: 'eip155',
    chain_identifier: 9,
    name: 'Quai Network Mainnet',
    native_coin_id: 'QUAI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_quai.jpg',
    gecko_id: 'quai-network',
  },
  {
    caip: 'eip155:622277',
    namespace: 'eip155',
    chain_identifier: 622277,
    name: 'Hypra Mainnet',
    native_coin_id: 'HYP',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/195/small/hypra.jpeg?1709713617',
    gecko_id: 'hypra-network',
  },
  {
    caip: 'eip155:3797',
    namespace: 'eip155',
    chain_identifier: 3797,
    name: 'AlveyChain Mainnet',
    native_coin_id: 'ALV',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/309/small/alvey.jpeg?1724918370',
    gecko_id: 'alverychain',
  },
  {
    caip: 'eip155:361',
    namespace: 'eip155',
    chain_identifier: 361,
    name: 'Theta Mainnet',
    native_coin_id: 'TFUEL',
    image: 'https://icons.llamao.fi/icons/chains/rsz_theta.jpg',
    gecko_id: 'theta-token',
  },
  {
    caip: 'eip155:100',
    namespace: 'eip155',
    chain_identifier: 100,
    name: 'Gnosis',
    native_coin_id: 'XDAI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_xdai.jpg',
    gecko_id: 'gnosis',
  },
  {
    caip: 'eip155:810180',
    namespace: 'eip155',
    chain_identifier: 810180,
    name: 'zkLink Nova Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zklink%20nova.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:2040',
    namespace: 'eip155',
    chain_identifier: 2040,
    name: 'Vanar Mainnet',
    native_coin_id: 'VANRY',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/269/small/vanar.jpeg?1717500553',
    gecko_id: 'vanar-chain',
  },
  {
    caip: 'eip155:106',
    namespace: 'eip155',
    chain_identifier: 106,
    name: 'Velas EVM Mainnet',
    native_coin_id: 'VLX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_velas.jpg',
    gecko_id: 'velas',
  },
  {
    caip: 'eip155:333000333',
    namespace: 'eip155',
    chain_identifier: 333000333,
    name: 'Meld',
    native_coin_id: 'gMELD',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/173/small/meld.jpeg?1706606800',
    gecko_id: 'meld',
  },
  {
    caip: 'eip155:1111',
    namespace: 'eip155',
    chain_identifier: 1111,
    name: 'WEMIX3.0 Mainnet',
    native_coin_id: 'WEMIX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/113/small/wemix.png?1706606488',
    gecko_id: 'wemix-network',
  },
  {
    caip: 'eip155:22776',
    namespace: 'eip155',
    chain_identifier: 22776,
    name: 'MAP Protocol',
    native_coin_id: 'MAPO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_map%20protocol.jpg',
    gecko_id: 'map-protocol',
  },
  {
    caip: 'eip155:52',
    namespace: 'eip155',
    chain_identifier: 52,
    name: 'CoinEx Smart Chain Mainnet',
    native_coin_id: 'cet',
    image: 'https://icons.llamao.fi/icons/chains/rsz_csc.jpg',
    gecko_id: 'coinex-token',
  },
  {
    caip: 'eip155:239',
    namespace: 'eip155',
    chain_identifier: 239,
    name: 'TAC Mainnet',
    native_coin_id: 'TAC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_tac.jpg',
    gecko_id: 'tac',
  },
  {
    caip: 'eip155:137',
    namespace: 'eip155',
    chain_identifier: 137,
    name: 'Polygon Mainnet',
    native_coin_id: 'POL',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/137/native.webp',
    gecko_id: 'polygon-ecosystem-token',
  },
  {
    caip: 'eip155:5234',
    namespace: 'eip155',
    chain_identifier: 5234,
    name: 'Humanode Mainnet',
    native_coin_id: 'eHMND',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/161/small/humanode.png?1706606654',
    gecko_id: 'humanode',
  },
  {
    caip: 'eip155:7778',
    namespace: 'eip155',
    chain_identifier: 7778,
    name: 'Orenium Mainnet Protocol',
    native_coin_id: 'ORE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/233/small/orenium.png?1712550641',
    gecko_id: 'orenium',
  },
  {
    caip: 'eip155:1209',
    namespace: 'eip155',
    chain_identifier: 1209,
    name: 'SaitaBlockChain(SBC)',
    native_coin_id: 'STC',
    image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20513.png',
    gecko_id: 'saita-chain',
  },
  {
    caip: 'eip155:42262',
    namespace: 'eip155',
    chain_identifier: 42262,
    name: 'Oasis Emerald',
    native_coin_id: 'ROSE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_oasis.jpg',
    gecko_id: 'oasis-network',
  },
  {
    caip: 'eip155:1666600000',
    namespace: 'eip155',
    chain_identifier: 1666600000,
    name: 'Harmony Mainnet Shard 0',
    native_coin_id: 'ONE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_harmony.jpg',
    gecko_id: 'harmony',
  },
  {
    caip: 'eip155:70',
    namespace: 'eip155',
    chain_identifier: 70,
    name: 'Hoo Smart Chain',
    native_coin_id: 'HOO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_hoo.jpg',
    gecko_id: 'hoo-token',
  },
  {
    caip: 'eip155:27563',
    namespace: 'eip155',
    chain_identifier: 27563,
    name: 'Onchain',
    native_coin_id: null,
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/311/small/bpmi3su1uwpri22dtmlqhnwgr3ip.png?1725610791',
    gecko_id: null,
  },
  {
    caip: 'eip155:1907',
    namespace: 'eip155',
    chain_identifier: 1907,
    name: 'Bitcichain Mainnet',
    native_coin_id: 'BITCI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bitcichain.jpg',
    gecko_id: 'bitcicoin',
  },
  {
    caip: 'eip155:988',
    namespace: 'eip155',
    chain_identifier: 988,
    name: 'Stable Mainnet',
    native_coin_id: 'USDT0',
    image: 'https://icons.llamao.fi/icons/chains/rsz_seda.jpg',
    gecko_id: 'stable-2',
  },
  {
    caip: 'eip155:3073',
    namespace: 'eip155',
    chain_identifier: 3073,
    name: 'Movement EVM',
    native_coin_id: 'MOVE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_move.jpg',
    gecko_id: 'movement',
  },
  {
    caip: 'eip155:1116',
    namespace: 'eip155',
    chain_identifier: 1116,
    name: 'Core Blockchain Mainnet',
    native_coin_id: 'CORE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_core.jpg',
    gecko_id: 'core',
  },
  {
    caip: 'eip155:6001',
    namespace: 'eip155',
    chain_identifier: 6001,
    name: 'BounceBit Mainnet',
    native_coin_id: 'BB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bouncebit.jpg',
    gecko_id: 'bouncebit',
  },
  {
    caip: 'eip155:333999',
    namespace: 'eip155',
    chain_identifier: 333999,
    name: 'Polis Mainnet',
    native_coin_id: 'POLIS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_polis.jpg',
    gecko_id: 'polis',
  },
  {
    caip: 'eip155:17777',
    namespace: 'eip155',
    chain_identifier: 17777,
    name: 'EOS EVM Network',
    native_coin_id: 'EOS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_eos%20evm.jpg',
    gecko_id: 'eos-evm',
  },
  {
    caip: 'eip155:1231',
    namespace: 'eip155',
    chain_identifier: 1231,
    name: 'Ultron Mainnet',
    native_coin_id: 'ULX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_ultron.jpg',
    gecko_id: 'ultron',
  },
  {
    caip: 'eip155:1559',
    namespace: 'eip155',
    chain_identifier: 1559,
    name: 'Tenet',
    native_coin_id: 'TENET',
    image: 'https://icons.llamao.fi/icons/chains/rsz_tenet.jpg',
    gecko_id: 'tenet',
  },
  {
    caip: 'eip155:88888',
    namespace: 'eip155',
    chain_identifier: 88888,
    name: 'Chiliz Chain Mainnet',
    native_coin_id: 'CHZ',
    image: 'https://icons.llamao.fi/icons/chains/rsz_chiliz.jpg',
    gecko_id: 'chiliz',
  },
  {
    caip: 'eip155:570',
    namespace: 'eip155',
    chain_identifier: 570,
    name: 'Rollux Mainnet',
    native_coin_id: 'SYS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_rollux.jpg',
    gecko_id: 'rollux',
  },
  {
    caip: 'eip155:34443',
    namespace: 'eip155',
    chain_identifier: 34443,
    name: 'Mode',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_mode.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:143',
    namespace: 'eip155',
    chain_identifier: 143,
    name: 'Monad',
    native_coin_id: 'MON',
    image: 'https://icons.llamao.fi/icons/chains/rsz_monad.jpg',
    gecko_id: 'monad',
  },
  {
    caip: 'eip155:19',
    namespace: 'eip155',
    chain_identifier: 19,
    name: 'Songbird Canary-Network',
    native_coin_id: 'SGB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_songbird.jpg',
    gecko_id: 'songbird',
  },
  {
    caip: 'eip155:1597',
    namespace: 'eip155',
    chain_identifier: 1597,
    name: 'Reactive Mainnet',
    native_coin_id: 'REACT',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22231/small/Symbol_ColorBlack_H32.png?1747974794',
    gecko_id: 'reactive-network',
  },
  {
    caip: 'eip155:148',
    namespace: 'eip155',
    chain_identifier: 148,
    name: 'ShimmerEVM',
    native_coin_id: 'SMR',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/154/small/shimmer.jpeg?1706606407',
    gecko_id: 'shimmer',
  },
  {
    caip: 'eip155:998',
    namespace: 'eip155',
    chain_identifier: 998,
    name: 'Hyperliquid EVM Testnet',
    native_coin_id: 'HYPE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/243/small/hyperliquid.png?1713924434',
    gecko_id: 'hyperliquid',
  },
  {
    caip: 'eip155:3011',
    namespace: 'eip155',
    chain_identifier: 3011,
    name: 'PLAYA3ULL GAMES',
    native_coin_id: '3ULL',
    image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/26863.png',
    gecko_id: 'playa3ull-games',
  },
  {
    caip: 'eip155:9008',
    namespace: 'eip155',
    chain_identifier: 9008,
    name: 'Shido Network',
    native_coin_id: 'SHIDO',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22202/small/shido.jpg?1738909286',
    gecko_id: 'shido',
  },
  {
    caip: 'eip155:81457',
    namespace: 'eip155',
    chain_identifier: 81457,
    name: 'Blast',
    native_coin_id: 'ETH',
    image: 'https://chain-icons.s3.amazonaws.com/chainlist/81457',
    gecko_id: 'blast',
  },
  {
    caip: 'eip155:11820',
    namespace: 'eip155',
    chain_identifier: 11820,
    name: 'Artela Mainnet',
    native_coin_id: 'ART',
    image: 'https://icons.llamao.fi/icons/chains/rsz_artela.jpg',
    gecko_id: 'artela-network',
  },
  {
    caip: 'eip155:2366',
    namespace: 'eip155',
    chain_identifier: 2366,
    name: 'KiteAI',
    native_coin_id: 'KITE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/102132281/small/kite-logo.png?1770089842',
    gecko_id: 'kiteai',
  },
  {
    caip: 'eip155:766',
    namespace: 'eip155',
    chain_identifier: 766,
    name: 'QL1',
    native_coin_id: 'QOM',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22176/small/qom.png?1727689494',
    gecko_id: 'ql1',
  },
  {
    caip: 'eip155:520',
    namespace: 'eip155',
    chain_identifier: 520,
    name: 'XT Smart Chain Mainnet',
    native_coin_id: 'XT',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/285/small/xt.jpg?1722395971',
    gecko_id: 'xt-smart-chain',
  },
  {
    caip: 'eip155:648',
    namespace: 'eip155',
    chain_identifier: 648,
    name: 'Endurance Smart Chain Mainnet',
    native_coin_id: 'ACE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_endurance.jpg',
    gecko_id: 'endurance',
  },
  {
    caip: 'eip155:32520',
    namespace: 'eip155',
    chain_identifier: 32520,
    name: 'Bitgert Mainnet',
    native_coin_id: 'Brise',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bitgert.jpg',
    gecko_id: 'bitrise-token',
  },
  {
    caip: 'eip155:7887',
    namespace: 'eip155',
    chain_identifier: 7887,
    name: 'Kinto Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kinto.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:3721',
    namespace: 'eip155',
    chain_identifier: 3721,
    name: 'Xone Mainnet',
    native_coin_id: 'XOC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_xone%20chain.jpg',
    gecko_id: 'xoc',
  },
  {
    caip: 'eip155:42',
    namespace: 'eip155',
    chain_identifier: 42,
    name: 'LUKSO Mainnet',
    native_coin_id: 'LYX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_lukso.jpg',
    gecko_id: 'lukso-token-2',
  },
  {
    caip: 'eip155:1300',
    namespace: 'eip155',
    chain_identifier: 1300,
    name: 'Glue Mainnet',
    native_coin_id: 'GLUE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32244/small/glue.png?1752127434',
    gecko_id: 'glue',
  },
  {
    caip: 'eip155:800001',
    namespace: 'eip155',
    chain_identifier: 800001,
    name: 'OctaSpace',
    native_coin_id: 'OCTA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/249/small/octaspace.jpeg?1714442969',
    gecko_id: 'octaspace',
  },
  {
    caip: 'eip155:6942',
    namespace: 'eip155',
    chain_identifier: 6942,
    name: 'Laika Mainnet',
    native_coin_id: 'DOGE',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22187/small/laika_chain.jpg?1731895152',
    gecko_id: 'laikachain',
  },
  {
    caip: 'eip155:1339',
    namespace: 'eip155',
    chain_identifier: 1339,
    name: 'Elysium Mainnet',
    native_coin_id: 'ELY',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/303/small/elysium.jpeg?1724915402',
    gecko_id: 'elysium',
  },
  {
    caip: 'eip155:108160679',
    namespace: 'eip155',
    chain_identifier: 108160679,
    name: 'Oraichain Mainnet',
    native_coin_id: 'ORAI',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/252/small/oraichain.jpeg?1714730939',
    gecko_id: 'oraichain',
  },
  {
    caip: 'eip155:1313161554',
    namespace: 'eip155',
    chain_identifier: 1313161554,
    name: 'Aurora Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_aurora.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:42220',
    namespace: 'eip155',
    chain_identifier: 42220,
    name: 'Celo Mainnet',
    native_coin_id: 'CELO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_celo.jpg',
    gecko_id: 'celo',
  },
  {
    caip: 'eip155:88',
    namespace: 'eip155',
    chain_identifier: 88,
    name: 'Viction',
    native_coin_id: 'VIC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_tomochain.jpg',
    gecko_id: 'tomochain',
  },
  {
    caip: 'eip155:39797',
    namespace: 'eip155',
    chain_identifier: 39797,
    name: 'Energi Mainnet',
    native_coin_id: 'NRG',
    image: 'https://icons.llamao.fi/icons/chains/rsz_energi.jpg',
    gecko_id: 'energi',
  },
  {
    caip: 'eip155:9001',
    namespace: 'eip155',
    chain_identifier: 9001,
    name: 'Evmos',
    native_coin_id: 'EVMOS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_evmos.jpg',
    gecko_id: 'evmos',
  },
  {
    caip: 'eip155:4689',
    namespace: 'eip155',
    chain_identifier: 4689,
    name: 'IoTeX Network Mainnet',
    native_coin_id: 'IOTX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_iotex.jpg',
    gecko_id: 'iotex',
  },
  {
    caip: 'eip155:592',
    namespace: 'eip155',
    chain_identifier: 592,
    name: 'Astar',
    native_coin_id: 'ASTR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_astar.jpg',
    gecko_id: 'astar',
  },
  {
    caip: 'eip155:122',
    namespace: 'eip155',
    chain_identifier: 122,
    name: 'Fuse Mainnet',
    native_coin_id: 'FUSE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_fuse.jpg',
    gecko_id: 'fuse-network-token',
  },
  {
    caip: 'eip155:1750',
    namespace: 'eip155',
    chain_identifier: 1750,
    name: 'Metal L2',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22174/small/metal.jpg?1727078117',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:8899',
    namespace: 'eip155',
    chain_identifier: 8899,
    name: 'JIBCHAIN L1',
    native_coin_id: 'JBC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_jbc.jpg',
    gecko_id: 'jibchain',
  },
  {
    caip: 'eip155:288623',
    namespace: 'eip155',
    chain_identifier: 288623,
    name: 'ValueChain',
    native_coin_id: null,
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32277/small/photo_2026-01-07_17.01.59.jpeg?1767776546',
    gecko_id: 'valuechain',
  },
  {
    caip: 'eip155:888',
    namespace: 'eip155',
    chain_identifier: 888,
    name: 'Wanchain',
    native_coin_id: 'WAN',
    image: 'https://icons.llamao.fi/icons/chains/rsz_wanchain.jpg',
    gecko_id: 'wanchain',
  },
  {
    caip: 'eip155:199',
    namespace: 'eip155',
    chain_identifier: 199,
    name: 'BitTorrent Chain Mainnet',
    native_coin_id: 'BTT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bittorrent.jpg',
    gecko_id: 'bittorrent',
  },
  {
    caip: 'eip155:20',
    namespace: 'eip155',
    chain_identifier: 20,
    name: 'Elastos Smart Chain',
    native_coin_id: 'ELA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_elastos.jpg',
    gecko_id: 'elastos',
  },
  {
    caip: 'eip155:10000',
    namespace: 'eip155',
    chain_identifier: 10000,
    name: 'Smart Bitcoin Cash',
    native_coin_id: 'BCH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_smartbch.jpg',
    gecko_id: 'bitcoin-cash',
  },
  {
    caip: 'eip155:1234',
    namespace: 'eip155',
    chain_identifier: 1234,
    name: 'Step Network',
    native_coin_id: 'FITFI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_step.jpg',
    gecko_id: 'step-network',
  },
  {
    caip: 'eip155:108',
    namespace: 'eip155',
    chain_identifier: 108,
    name: 'ThunderCore Mainnet',
    native_coin_id: 'TT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_thundercore.jpg',
    gecko_id: 'thunder-token',
  },
  {
    caip: 'eip155:18159',
    namespace: 'eip155',
    chain_identifier: 18159,
    name: 'Proof Of Memes',
    native_coin_id: 'POM',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/112/small/proof_of_meme.jpeg?1706606430',
    gecko_id: 'proof-of-memes',
  },
  {
    caip: 'eip155:2016',
    namespace: 'eip155',
    chain_identifier: 2016,
    name: 'MainnetZ Mainnet',
    native_coin_id: 'NetZ',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/282/small/MainnetZ.png?1724842719',
    gecko_id: 'mainnetz',
  },
  {
    caip: 'eip155:322202',
    namespace: 'eip155',
    chain_identifier: 322202,
    name: 'Parex Mainnet',
    native_coin_id: 'PRX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_parex.jpg',
    gecko_id: 'parex',
  },
  {
    caip: 'eip155:463',
    namespace: 'eip155',
    chain_identifier: 463,
    name: 'Areon Network Mainnet',
    native_coin_id: 'AREA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/172/small/areon.jpeg?1706606591',
    gecko_id: 'areon-network',
  },
  {
    caip: 'eip155:8822',
    namespace: 'eip155',
    chain_identifier: 8822,
    name: 'IOTA EVM',
    native_coin_id: 'IOTA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_iota%20evm.jpg',
    gecko_id: 'iota',
  },
  {
    caip: 'eip155:4061',
    namespace: 'eip155',
    chain_identifier: 4061,
    name: 'Nahmii 3 Mainnet',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/270/small/nahmii.jpeg?1717568564',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:56288',
    namespace: 'eip155',
    chain_identifier: 56288,
    name: 'Boba BNB Mainnet',
    native_coin_id: 'BOBA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_boba_bnb.jpg',
    gecko_id: 'boba-bnb',
  },
  {
    caip: 'eip155:43419',
    namespace: 'eip155',
    chain_identifier: 43419,
    name: 'GUNZ',
    native_coin_id: 'GUN',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32246/small/gunz.jpg?1753065139',
    gecko_id: 'gunz',
  },
  {
    caip: 'eip155:8889',
    namespace: 'eip155',
    chain_identifier: 8889,
    name: 'Vyvo Smart Chain',
    native_coin_id: 'VSC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/274/small/Vyvo.jpg?1724843210',
    gecko_id: 'vyvo-smart-chain',
  },
  {
    caip: 'eip155:5464',
    namespace: 'eip155',
    chain_identifier: 5464,
    name: 'SagaEVM',
    native_coin_id: 'GAS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_saga.jpg',
    gecko_id: 'saga-2',
  },
  {
    caip: 'eip155:248',
    namespace: 'eip155',
    chain_identifier: 248,
    name: 'Oasys Mainnet',
    native_coin_id: 'OAS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_oasys.jpg',
    gecko_id: 'oasys',
  },
  {
    caip: 'eip155:11235',
    namespace: 'eip155',
    chain_identifier: 11235,
    name: 'Haqq Network',
    native_coin_id: 'ISLM',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/272/small/haqq-sign.png?1717594659',
    gecko_id: 'islamic-coin',
  },
  {
    caip: 'eip155:33979',
    namespace: 'eip155',
    chain_identifier: 33979,
    name: 'Funki',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22204/small/funki.jpg?1738923402',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:169',
    namespace: 'eip155',
    chain_identifier: 169,
    name: 'Manta Pacific Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_manta.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:288',
    namespace: 'eip155',
    chain_identifier: 288,
    name: 'Boba Network',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_boba.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:1996',
    namespace: 'eip155',
    chain_identifier: 1996,
    name: 'Sanko',
    native_coin_id: 'DMT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sanko.jpg',
    gecko_id: 'dream-machine-token',
  },
  {
    caip: 'eip155:7171',
    namespace: 'eip155',
    chain_identifier: 7171,
    name: 'Bitrock Mainnet',
    native_coin_id: 'BROCK',
    image: 'https://icons.llamao.fi/icons/chains/rsz_bitrock.jpg',
    gecko_id: 'bitrock',
  },
  {
    caip: 'eip155:196',
    namespace: 'eip155',
    chain_identifier: 196,
    name: 'X Layer Mainnet',
    native_coin_id: 'OKB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_x%20layer.jpg',
    gecko_id: 'x-layer',
  },
  {
    caip: 'eip155:1285',
    namespace: 'eip155',
    chain_identifier: 1285,
    name: 'Moonriver',
    native_coin_id: 'MOVR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_moonriver.jpg',
    gecko_id: 'moonriver',
  },
  {
    caip: 'eip155:1030',
    namespace: 'eip155',
    chain_identifier: 1030,
    name: 'Conflux eSpace',
    native_coin_id: 'CFX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_conflux.jpg',
    gecko_id: 'conflux',
  },
  {
    caip: 'eip155:61',
    namespace: 'eip155',
    chain_identifier: 61,
    name: 'Ethereum Classic',
    native_coin_id: 'ETC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_ethereumclassic.jpg',
    gecko_id: 'ethereum-classic',
  },
  {
    caip: 'eip155:128',
    namespace: 'eip155',
    chain_identifier: 128,
    name: 'Huobi ECO Chain Mainnet',
    native_coin_id: 'HT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_heco.jpg',
    gecko_id: 'huobi-token',
  },
  {
    caip: 'eip155:321',
    namespace: 'eip155',
    chain_identifier: 321,
    name: 'KCC Mainnet',
    native_coin_id: 'KCS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kucoin.jpg',
    gecko_id: 'kucoin-shares',
  },
  {
    caip: 'eip155:813',
    namespace: 'eip155',
    chain_identifier: 813,
    name: 'Qitmeer Network Mainnet',
    native_coin_id: 'MEER',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/297/small/qitmeer.jpeg?1724912468',
    gecko_id: 'qitmeer-network',
  },
  {
    caip: 'eip155:82',
    namespace: 'eip155',
    chain_identifier: 82,
    name: 'Meter Mainnet',
    native_coin_id: 'MTR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_meter.jpg',
    gecko_id: 'meter',
  },
  {
    caip: 'eip155:100009',
    namespace: 'eip155',
    chain_identifier: 100009,
    name: 'VeChain',
    native_coin_id: 'VET',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/1167/small/vechain.png?1724843001',
    gecko_id: 'vechain',
  },
  {
    caip: 'eip155:73115',
    namespace: 'eip155',
    chain_identifier: 73115,
    name: 'ICB Network',
    native_coin_id: 'ICBX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22210/small/icbx.jpg?1740645694',
    gecko_id: 'icb-network',
  },
  {
    caip: 'eip155:5888',
    namespace: 'eip155',
    chain_identifier: 5888,
    name: 'MANTRACHAIN Mainnet',
    native_coin_id: 'OM',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32275/small/logo.png?1766376333',
    gecko_id: 'mantra-evm',
  },
  {
    caip: 'eip155:210425',
    namespace: 'eip155',
    chain_identifier: 210425,
    name: 'PlatON Mainnet',
    native_coin_id: 'lat',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/292/small/PlatON-Black.png?1724840056',
    gecko_id: 'platon-network',
  },
  {
    caip: 'eip155:18686',
    namespace: 'eip155',
    chain_identifier: 18686,
    name: 'MXC zkEVM Moonchain',
    native_coin_id: 'MXC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_moonchain.jpg',
    gecko_id: 'mxc',
  },
  {
    caip: 'eip155:10201',
    namespace: 'eip155',
    chain_identifier: 10201,
    name: 'MaxxChain Mainnet',
    native_coin_id: 'PWR',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/301/small/maxxchain.png?1724913995',
    gecko_id: 'maxxchain',
  },
  {
    caip: 'eip155:841',
    namespace: 'eip155',
    chain_identifier: 841,
    name: 'Taraxa Mainnet',
    native_coin_id: 'TARA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22183/small/taraxa.jpg?1749459522',
    gecko_id: 'taraxa',
  },
  {
    caip: 'eip155:614',
    namespace: 'eip155',
    chain_identifier: 614,
    name: 'Graphlinq Blockchain Mainnet',
    native_coin_id: 'GLQ',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/306/small/graphlinq.jpeg?1724916874',
    gecko_id: 'graphlinq-chain',
  },
  {
    caip: 'eip155:62621',
    namespace: 'eip155',
    chain_identifier: 62621,
    name: 'MultiVAC Mainnet',
    native_coin_id: 'MTV',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/307/small/multivac.jpeg?1724917227',
    gecko_id: 'multivac',
  },
  {
    caip: 'eip155:42161',
    namespace: 'eip155',
    chain_identifier: 42161,
    name: 'Arbitrum One',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/42161/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:9898',
    namespace: 'eip155',
    chain_identifier: 9898,
    name: 'Larissa Chain',
    native_coin_id: 'LRS',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/305/small/larissa.jpeg?1724916642',
    gecko_id: 'larissa',
  },
  {
    caip: 'eip155:9980',
    namespace: 'eip155',
    chain_identifier: 9980,
    name: 'Combo Mainnet',
    native_coin_id: 'BNB',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/304/small/combo.jpeg?1724916064',
    gecko_id: 'binancecoin',
  },
  {
    caip: 'eip155:8668',
    namespace: 'eip155',
    chain_identifier: 8668,
    name: 'Hela Official Runtime Mainnet',
    native_coin_id: 'HLUSD',
    image: 'https://icons.llamao.fi/icons/chains/rsz_hela.jpg',
    gecko_id: 'hela',
  },
  {
    caip: 'eip155:5330',
    namespace: 'eip155',
    chain_identifier: 5330,
    name: 'Superseed',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_superseed.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:6900',
    namespace: 'eip155',
    chain_identifier: 6900,
    name: 'Nibiru cataclysm-1',
    native_coin_id: 'NIBI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_nibiru.jpg',
    gecko_id: 'nibiru',
  },
  {
    caip: 'eip155:336',
    namespace: 'eip155',
    chain_identifier: 336,
    name: 'Shiden',
    native_coin_id: 'SDN',
    image: 'https://icons.llamao.fi/icons/chains/rsz_shiden.jpg',
    gecko_id: 'shiden',
  },
  {
    caip: 'eip155:161803',
    namespace: 'eip155',
    chain_identifier: 161803,
    name: 'Eventum Mainnet',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32251/small/eventum.png?1755149230',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:177',
    namespace: 'eip155',
    chain_identifier: 177,
    name: 'HashKey Chain',
    native_coin_id: 'HSK',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32250/small/hashkey.jpg?1754898883',
    gecko_id: 'hashkey-ecopoints',
  },
  {
    caip: 'eip155:30',
    namespace: 'eip155',
    chain_identifier: 30,
    name: 'Rootstock Mainnet',
    native_coin_id: 'RBTC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_rsk.jpg',
    gecko_id: 'rootstock',
  },
  {
    caip: 'eip155:255',
    namespace: 'eip155',
    chain_identifier: 255,
    name: 'Kroma',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kroma.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:2000',
    namespace: 'eip155',
    chain_identifier: 2000,
    name: 'Dogechain Mainnet',
    native_coin_id: 'DOGE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_dogechain.jpg',
    gecko_id: 'dogechain',
  },
  {
    caip: 'eip155:213',
    namespace: 'eip155',
    chain_identifier: 213,
    name: 'B2 Hub Mainnet',
    native_coin_id: 'B2',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/239/small/bsquared-network.jpeg?1713432732',
    gecko_id: 'bsquared-network',
  },
  {
    caip: 'eip155:1625',
    namespace: 'eip155',
    chain_identifier: 1625,
    name: 'Gravity Alpha Mainnet',
    native_coin_id: 'G',
    image: 'https://icons.llamao.fi/icons/chains/rsz_gravity.jpg',
    gecko_id: 'g-token',
  },
  {
    caip: 'eip155:16718',
    namespace: 'eip155',
    chain_identifier: 16718,
    name: 'AirDAO Mainnet',
    native_coin_id: 'AMB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_airdao.jpg',
    gecko_id: 'amber',
  },
  {
    caip: 'eip155:50',
    namespace: 'eip155',
    chain_identifier: 50,
    name: 'XDC Network',
    native_coin_id: 'XDC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_xdc.jpg',
    gecko_id: 'xdc-network',
  },
  {
    caip: 'eip155:2046399126',
    namespace: 'eip155',
    chain_identifier: 2046399126,
    name: 'SKALE Europa Hub',
    native_coin_id: 'sFUEL',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/96/small/skale.png?1706606673',
    gecko_id: 'skale',
  },
  {
    caip: 'eip155:57',
    namespace: 'eip155',
    chain_identifier: 57,
    name: 'Syscoin Mainnet',
    native_coin_id: 'SYS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_syscoin.jpg',
    gecko_id: 'syscoin',
  },
  {
    caip: 'eip155:146',
    namespace: 'eip155',
    chain_identifier: 146,
    name: 'Sonic Mainnet',
    native_coin_id: 'S',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sonic.jpg',
    gecko_id: 'sonic-3',
  },
  {
    caip: 'eip155:5545',
    namespace: 'eip155',
    chain_identifier: 5545,
    name: 'DuckChain Mainnet',
    native_coin_id: 'TON',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22190/small/duckchain.jpg?1733401377',
    gecko_id: 'duckchain',
  },
  {
    caip: 'eip155:1480',
    namespace: 'eip155',
    chain_identifier: 1480,
    name: 'Vana',
    native_coin_id: 'VANA',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22198/small/vana.jpg?1735899932',
    gecko_id: 'vana',
  },
  {
    caip: 'eip155:250',
    namespace: 'eip155',
    chain_identifier: 250,
    name: 'Fantom Opera',
    native_coin_id: 'FTM',
    image: 'https://icons.llamao.fi/icons/chains/rsz_fantom.jpg',
    gecko_id: 'fantom',
  },
  {
    caip: 'eip155:4158',
    namespace: 'eip155',
    chain_identifier: 4158,
    name: 'CrossFi Mainnet',
    native_coin_id: 'XFI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_crossfi.jpg',
    gecko_id: 'crossfi-2',
  },
  {
    caip: 'eip155:68414',
    namespace: 'eip155',
    chain_identifier: 68414,
    name: 'Henesys',
    native_coin_id: 'NXPC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32272/small/MSU.png?1765786624',
    gecko_id: 'henesys',
  },
  {
    caip: 'eip155:19880818',
    namespace: 'eip155',
    chain_identifier: 19880818,
    name: 'DeepBrainChain Mainnet',
    native_coin_id: 'DBC',
    image:
      'https://assets.coingecko.com/coins/images/2057/standard/DeepBrainChain.png?1696503024',
    gecko_id: 'deepbrain-chain',
  },
  {
    caip: 'eip155:4162',
    namespace: 'eip155',
    chain_identifier: 4162,
    name: 'SX Rollup',
    native_coin_id: 'SX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22219/small/sx_network.jpg?1744352289',
    gecko_id: 'sx-rollup',
  },
  {
    caip: 'eip155:88811',
    namespace: 'eip155',
    chain_identifier: 88811,
    name: 'Unit Zero Mainnet',
    native_coin_id: 'UNIT0',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22193/small/unit0.jpg?1734076011',
    gecko_id: 'units-network',
  },
  {
    caip: 'eip155:32769',
    namespace: 'eip155',
    chain_identifier: 32769,
    name: 'Zilliqa 2',
    native_coin_id: 'ZIL',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zilliqa.jpg',
    gecko_id: 'zilliqa-evm',
  },
  {
    caip: 'eip155:440017',
    namespace: 'eip155',
    chain_identifier: 440017,
    name: 'Graphite Mainnet',
    native_coin_id: '@G',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22220/small/graphite_network.jpg?1744596598',
    gecko_id: 'graphite-network',
  },
  {
    caip: 'eip155:52014',
    namespace: 'eip155',
    chain_identifier: 52014,
    name: 'Electroneum Mainnet',
    native_coin_id: 'ETN',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22214/small/electroneum.jpg?1741575232',
    gecko_id: 'electroneum',
  },
  {
    caip: 'eip155:8811',
    namespace: 'eip155',
    chain_identifier: 8811,
    name: 'Haven1',
    native_coin_id: 'H1',
    image: 'https://icons.llamao.fi/icons/chains/rsz_haven1.jpg',
    gecko_id: 'haven1',
  },
  {
    caip: 'eip155:2632500',
    namespace: 'eip155',
    chain_identifier: 2632500,
    name: 'COTI',
    native_coin_id: 'COTI',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32274/small/coti.jpg?1765937321',
    gecko_id: 'coti',
  },
  {
    caip: 'eip155:1514',
    namespace: 'eip155',
    chain_identifier: 1514,
    name: 'Story',
    native_coin_id: 'IP',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sty.jpg',
    gecko_id: 'story-2',
  },
  {
    caip: 'eip155:4352',
    namespace: 'eip155',
    chain_identifier: 4352,
    name: 'MemeCore',
    native_coin_id: 'M',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32243/small/memecore.jpg?1752116020',
    gecko_id: 'memecore',
  },
  {
    caip: 'eip155:480',
    namespace: 'eip155',
    chain_identifier: 480,
    name: 'World Chain',
    native_coin_id: 'ETH',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/22180/small/Worldcoin-logomark-light.png?1728377966',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:222222',
    namespace: 'eip155',
    chain_identifier: 222222,
    name: 'Hydration',
    native_coin_id: 'WETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_hydradx.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:5000',
    namespace: 'eip155',
    chain_identifier: 5000,
    name: 'Mantle',
    native_coin_id: 'MNT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_mantle.jpg',
    gecko_id: 'mantle',
  },
  {
    caip: 'eip155:10',
    namespace: 'eip155',
    chain_identifier: 10,
    name: 'Optimism',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/10/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:59144',
    namespace: 'eip155',
    chain_identifier: 59144,
    name: 'Linea',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/59144/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:1284',
    namespace: 'eip155',
    chain_identifier: 1284,
    name: 'Moonbeam',
    native_coin_id: 'GLMR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_moonbeam.jpg',
    gecko_id: 'moonbeam',
  },
  {
    caip: 'eip155:119',
    namespace: 'eip155',
    chain_identifier: 119,
    name: 'ENULS Mainnet',
    native_coin_id: 'NULS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_enuls.jpg',
    gecko_id: 'enuls',
  },
  {
    caip: 'eip155:7070',
    namespace: 'eip155',
    chain_identifier: 7070,
    name: 'Planq Mainnet',
    native_coin_id: 'PLQ',
    image: 'https://icons.llamao.fi/icons/chains/rsz_planq.jpg',
    gecko_id: 'planq',
  },
  {
    caip: 'eip155:111188',
    namespace: 'eip155',
    chain_identifier: 111188,
    name: 're.al',
    native_coin_id: 'reETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_real.jpg',
    gecko_id: 're-al',
  },
  {
    caip: 'eip155:11501',
    namespace: 'eip155',
    chain_identifier: 11501,
    name: 'GEB Mainnet',
    native_coin_id: 'BTC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/245/small/bevm.jpeg?1713945524',
    gecko_id: 'bevm',
  },
  {
    caip: 'eip155:369',
    namespace: 'eip155',
    chain_identifier: 369,
    name: 'PulseChain',
    native_coin_id: 'PLS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_pulse.jpg',
    gecko_id: 'pulsechain',
  },
  {
    caip: 'eip155:2818',
    namespace: 'eip155',
    chain_identifier: 2818,
    name: 'Morph',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_morph.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:41923',
    namespace: 'eip155',
    chain_identifier: 41923,
    name: 'EDU Chain',
    native_coin_id: 'EDU',
    image: 'https://icons.llamao.fi/icons/chains/rsz_edu chain.jpg',
    gecko_id: 'edu-coin',
  },
  {
    caip: 'eip155:7700',
    namespace: 'eip155',
    chain_identifier: 7700,
    name: 'Canto',
    native_coin_id: 'CANTO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_canto.jpg',
    gecko_id: 'canto',
  },
  {
    caip: 'eip155:33139',
    namespace: 'eip155',
    chain_identifier: 33139,
    name: 'ApeChain',
    native_coin_id: 'APE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_apechain.jpg',
    gecko_id: 'apecoin',
  },
  {
    caip: 'eip155:80094',
    namespace: 'eip155',
    chain_identifier: 80094,
    name: 'Berachain',
    native_coin_id: 'BERA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_berachain.jpg',
    gecko_id: 'berachain-bera',
  },
  {
    caip: 'eip155:660279',
    namespace: 'eip155',
    chain_identifier: 660279,
    name: 'Xai Mainnet',
    native_coin_id: 'XAI',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/189/small/xai.png?1708573604',
    gecko_id: 'xai',
  },
  {
    caip: 'eip155:10849',
    namespace: 'eip155',
    chain_identifier: 10849,
    name: 'Lamina1',
    native_coin_id: 'L1',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32258/small/lamina1.png?1758104636',
    gecko_id: 'lamina1',
  },
  {
    caip: 'eip155:2345',
    namespace: 'eip155',
    chain_identifier: 2345,
    name: 'GOAT Network',
    native_coin_id: 'BTC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_goat.jpg',
    gecko_id: 'goat-network',
  },
  {
    caip: 'eip155:153153',
    namespace: 'eip155',
    chain_identifier: 153153,
    name: 'Odyssey Chain Mainnet',
    native_coin_id: 'DIONE',
    image: 'https://icons.llamao.fi/icons/chains/rsz_odyssey.jpg',
    gecko_id: 'dione',
  },
  {
    caip: 'eip155:4326',
    namespace: 'eip155',
    chain_identifier: 4326,
    name: 'MegaETH Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_polymesh.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:5031',
    namespace: 'eip155',
    chain_identifier: 5031,
    name: 'Somnia Mainnet',
    native_coin_id: 'SOMI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_somnia.jpg',
    gecko_id: 'somnia',
  },
  {
    caip: 'eip155:1983',
    namespace: 'eip155',
    chain_identifier: 1983,
    name: 'Krown Mainnet',
    native_coin_id: 'KROWN',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/32279/small/krown.png?1768465763',
    gecko_id: 'krown-network',
  },
  {
    caip: 'eip155:8217',
    namespace: 'eip155',
    chain_identifier: 8217,
    name: 'Kaia Mainnet',
    native_coin_id: 'KAIA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_klaytn.jpg',
    gecko_id: 'klay-token',
  },
  {
    caip: 'eip155:56',
    namespace: 'eip155',
    chain_identifier: 56,
    name: 'BNB Smart Chain Mainnet',
    native_coin_id: 'BNB',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/56/native.webp',
    gecko_id: 'binancecoin',
  },
  {
    caip: 'eip155:1',
    namespace: 'eip155',
    chain_identifier: 1,
    name: 'Ethereum Mainnet',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/1/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:43114',
    namespace: 'eip155',
    chain_identifier: 43114,
    name: 'Avalanche C-Chain',
    native_coin_id: 'AVAX',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/43114/native.webp',
    gecko_id: 'avalanche-2',
  },
  {
    caip: 'eip155:1776',
    namespace: 'eip155',
    chain_identifier: 1776,
    name: 'Injective',
    native_coin_id: 'INJ',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/134/small/injective.jpeg?1706606600',
    gecko_id: 'injective',
  },
  {
    caip: 'eip155:25',
    namespace: 'eip155',
    chain_identifier: 25,
    name: 'Cronos Mainnet',
    native_coin_id: 'CRO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_cronos.jpg',
    gecko_id: 'crypto-com-chain',
  },
  {
    caip: 'eip155:13371',
    namespace: 'eip155',
    chain_identifier: 13371,
    name: 'Immutable zkEVM',
    native_coin_id: 'IMX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_immutable%20zkevm.jpg',
    gecko_id: 'immutable-x',
  },
  {
    caip: 'eip155:4200',
    namespace: 'eip155',
    chain_identifier: 4200,
    name: 'Merlin Mainnet',
    native_coin_id: 'BTC',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/188/small/merlin-chain.jpeg?1708522313',
    gecko_id: 'merlin-chain',
  },
  {
    caip: 'eip155:534352',
    namespace: 'eip155',
    chain_identifier: 534352,
    name: 'Scroll',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_scroll.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:14',
    namespace: 'eip155',
    chain_identifier: 14,
    name: 'Flare Mainnet',
    native_coin_id: 'FLR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_flare.jpg',
    gecko_id: 'flare-network',
  },
  {
    caip: 'eip155:324',
    namespace: 'eip155',
    chain_identifier: 324,
    name: 'zkSync Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zksync%20era.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:252',
    namespace: 'eip155',
    chain_identifier: 252,
    name: 'Fraxtal',
    native_coin_id: 'FRAX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_fraxtal.jpg',
    gecko_id: 'fraxtal',
  },
  {
    caip: 'eip155:666666666',
    namespace: 'eip155',
    chain_identifier: 666666666,
    name: 'Degen Chain',
    native_coin_id: 'DEGEN',
    image: 'https://icons.llamao.fi/icons/chains/rsz_degen.jpg',
    gecko_id: 'degen-base',
  },
  {
    caip: 'eip155:12553',
    namespace: 'eip155',
    chain_identifier: 12553,
    name: 'RSS3 VSL Mainnet',
    native_coin_id: 'RSS3',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/235/small/rss3_vsl.jpg?1733384918',
    gecko_id: 'rss3-vsl',
  },
  {
    caip: 'eip155:83872',
    namespace: 'eip155',
    chain_identifier: 83872,
    name: 'ZEDXION',
    native_coin_id: 'ZEDX',
    image:
      'https://coin-images.coingecko.com/asset_platforms/images/265/small/zedxion.png?1716526781',
    gecko_id: 'zedxion',
  },
  {
    caip: 'eip155:1329',
    namespace: 'eip155',
    chain_identifier: 1329,
    name: 'Sei Network',
    native_coin_id: 'SEI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_sei.jpg',
    gecko_id: 'sei-network',
  },
  {
    caip: 'eip155:295',
    namespace: 'eip155',
    chain_identifier: 295,
    name: 'Hedera Mainnet',
    native_coin_id: 'HBAR',
    image: 'https://icons.llamao.fi/icons/chains/rsz_hedera.jpg',
    gecko_id: 'hedera-hashgraph',
  },
  {
    caip: 'eip155:747',
    namespace: 'eip155',
    chain_identifier: 747,
    name: 'Flow EVM Mainnet',
    native_coin_id: 'FLOW',
    image: 'https://icons.llamao.fi/icons/chains/rsz_flow.jpg',
    gecko_id: 'flow',
  },
  {
    caip: 'eip155:3338',
    namespace: 'eip155',
    chain_identifier: 3338,
    name: 'peaq',
    native_coin_id: 'PEAQ',
    image: 'https://icons.llamao.fi/icons/chains/rsz_peaq.jpg',
    gecko_id: 'peaq-2',
  },
  {
    caip: 'eip155:7332',
    namespace: 'eip155',
    chain_identifier: 7332,
    name: 'Horizen EON Mainnet',
    native_coin_id: 'ZEN',
    image: 'https://icons.llamao.fi/icons/chains/rsz_horizen_eon.jpg',
    gecko_id: 'zencash',
  },
  {
    caip: 'eip155:47805',
    namespace: 'eip155',
    chain_identifier: 47805,
    name: 'REI Network',
    native_coin_id: 'REI',
    image: 'https://icons.llamao.fi/icons/chains/rsz_rei.jpg',
    gecko_id: 'rei-network',
  },
  {
    caip: 'eip155:1024',
    namespace: 'eip155',
    chain_identifier: 1024,
    name: 'CLV Parachain',
    native_coin_id: 'CLV',
    image: 'https://icons.llamao.fi/icons/chains/rsz_clv.jpg',
    gecko_id: 'clover-finance',
  },
  {
    caip: 'eip155:246',
    namespace: 'eip155',
    chain_identifier: 246,
    name: 'Energy Web Chain',
    native_coin_id: 'EWT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_energyweb.jpg',
    gecko_id: 'energy-web-token',
  },
  {
    caip: 'eip155:269',
    namespace: 'eip155',
    chain_identifier: 269,
    name: 'High Performance Blockchain',
    native_coin_id: 'HPB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_hpb.jpg',
    gecko_id: 'high-performance-blockchain',
  },
  {
    caip: 'eip155:32659',
    namespace: 'eip155',
    chain_identifier: 32659,
    name: 'Fusion Mainnet',
    native_coin_id: 'FSN',
    image: 'https://icons.llamao.fi/icons/chains/rsz_fusion.jpg',
    gecko_id: 'fsn',
  },
  {
    caip: 'eip155:55',
    namespace: 'eip155',
    chain_identifier: 55,
    name: 'Zyx Mainnet',
    native_coin_id: 'ZYX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_zyx.jpg',
    gecko_id: 'zyx',
  },
  {
    caip: 'eip155:8',
    namespace: 'eip155',
    chain_identifier: 8,
    name: 'Ubiq',
    native_coin_id: 'UBQ',
    image: 'https://icons.llamao.fi/icons/chains/rsz_ubiq.jpg',
    gecko_id: 'ubiq',
  },
  {
    caip: 'eip155:5551',
    namespace: 'eip155',
    chain_identifier: 5551,
    name: 'Nahmii 2 Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_nahmii.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:225',
    namespace: 'eip155',
    chain_identifier: 225,
    name: 'LACHAIN Mainnet',
    native_coin_id: 'LA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_lachain.jpg',
    gecko_id: 'latoken',
  },
  {
    caip: 'eip155:87',
    namespace: 'eip155',
    chain_identifier: 87,
    name: 'Nova Network',
    native_coin_id: 'SNT',
    image: 'https://icons.llamao.fi/icons/chains/rsz_nova%20network.jpg',
    gecko_id: 'supernova',
  },
  {
    caip: 'eip155:6699',
    namespace: 'eip155',
    chain_identifier: 6699,
    name: 'OX Chain',
    native_coin_id: 'OX',
    image: unknownLogo,
    gecko_id: 'ox-fun',
  },
  {
    caip: 'eip155:420420',
    namespace: 'eip155',
    chain_identifier: 420420,
    name: 'Kekchain',
    native_coin_id: 'KEK',
    image: 'https://icons.llamao.fi/icons/chains/rsz_kekchain.jpg',
    gecko_id: 'kekchain',
  },
  {
    caip: 'eip155:20402',
    namespace: 'eip155',
    chain_identifier: 20402,
    name: 'MUUCHAIN',
    native_coin_id: null,
    image: 'https://icons.llamao.fi/icons/chains/rsz_muuchain.jpg',
    gecko_id: 'muu-inu',
  },
  {
    caip: 'eip155:432204',
    namespace: 'eip155',
    chain_identifier: 432204,
    name: 'Dexalot Subnet',
    native_coin_id: 'ALOT',
    image:
      'https://raw.githubusercontent.com/Dexalot/tokenlist/refs/heads/main/imgs/dexalot_logo.png',
    gecko_id: 'dexalot',
  },
  {
    caip: 'eip155:44',
    namespace: 'eip155',
    chain_identifier: 44,
    name: 'Crab Network',
    native_coin_id: 'CRAB',
    image: 'https://icons.llamao.fi/icons/chains/rsz_crab.jpg',
    gecko_id: 'darwinia-crab-network',
  },
  {
    caip: 'eip155:254',
    namespace: 'eip155',
    chain_identifier: 254,
    name: 'Swan Chain Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_swan.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:256256',
    namespace: 'eip155',
    chain_identifier: 256256,
    name: 'CMP-Mainnet',
    native_coin_id: 'CMP',
    image: 'https://icons.llamao.fi/icons/chains/rsz_cmp.jpg',
    gecko_id: 'caduceus',
  },
  {
    caip: 'eip155:277',
    namespace: 'eip155',
    chain_identifier: 277,
    name: 'Prom',
    native_coin_id: null,
    image: 'https://icons.llamao.fi/icons/chains/rsz_prom.jpg',
    gecko_id: 'prometeus',
  },
  {
    caip: 'eip155:274',
    namespace: 'eip155',
    chain_identifier: 274,
    name: 'LaChain',
    native_coin_id: 'LAC',
    image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/27293.png',
    gecko_id: 'la-coin',
  },
  {
    caip: 'eip155:228',
    namespace: 'eip155',
    chain_identifier: 228,
    name: 'Mind Network Mainnet',
    native_coin_id: 'ETH',
    image: 'https://icons.llamao.fi/icons/chains/rsz_mind network.jpg',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:207',
    namespace: 'eip155',
    chain_identifier: 207,
    name: 'VinuChain Network',
    native_coin_id: 'VC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_vinuchain.jpg',
    gecko_id: 'vinuchain',
  },
  {
    caip: 'eip155:181',
    namespace: 'eip155',
    chain_identifier: 181,
    name: 'Waterfall Network',
    native_coin_id: 'WATER',
    image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/32282.png',
    gecko_id: 'water-3',
  },
  {
    caip: 'eip155:5887',
    namespace: 'eip155',
    chain_identifier: 5887,
    name: 'MANTRACHAIN Testnet',
    native_coin_id: 'MANTRA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_flynet.jpg',
    gecko_id: 'mantra-dao',
  },
  {
    caip: 'eip155:105105',
    namespace: 'eip155',
    chain_identifier: 105105,
    name: 'Xertra Mainnet',
    native_coin_id: 'STRAX',
    image: 'https://icons.llamao.fi/icons/chains/rsz_stratis.jpg',
    gecko_id: 'stratis',
  },
  {
    caip: 'eip155:20250217',
    namespace: 'eip155',
    chain_identifier: 20250217,
    name: 'Xphere Mainnet',
    native_coin_id: 'XP',
    image: 'https://icons.llamao.fi/icons/chains/rsz_xphere.jpg',
    gecko_id: 'xphere',
  },
  {
    caip: 'eip155:41455',
    namespace: 'eip155',
    chain_identifier: 41455,
    name: 'Aleph Zero EVM',
    native_coin_id: 'AZERO',
    image: 'https://icons.llamao.fi/icons/chains/rsz_aleph_zero_evm.jpg',
    gecko_id: 'aleph-zero',
  },
  {
    caip: 'eip155:5064014',
    namespace: 'eip155',
    chain_identifier: 5064014,
    name: 'Ethereal',
    native_coin_id: 'USDe',
    image: 'https://icons.llamao.fi/icons/chains/rsz_ethereal.jpg',
    gecko_id: 'ethena-usde',
  },
  {
    caip: 'eip155:757',
    namespace: 'eip155',
    chain_identifier: 757,
    name: 'Capx Chain',
    native_coin_id: 'CAPX',
    image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/36557.png',
    gecko_id: 'capx-ai',
  },
  {
    caip: 'eip155:612055',
    namespace: 'eip155',
    chain_identifier: 612055,
    name: 'CROSS',
    native_coin_id: 'CROSS',
    image: 'https://icons.llamao.fi/icons/chains/rsz_allora.jpg',
    gecko_id: 'cross-2',
  },
  {
    caip: 'eip155:4048',
    namespace: 'eip155',
    chain_identifier: 4048,
    name: 'GANchain L1',
    native_coin_id: 'GPU',
    image: 'https://icons.llamao.fi/icons/chains/rsz_earnm.jpg',
    gecko_id: 'gpunet',
  },
  {
    caip: 'eip155:81',
    namespace: 'eip155',
    chain_identifier: 81,
    name: 'Japan Open Chain Mainnet',
    native_coin_id: 'JOC',
    image: 'https://icons.llamao.fi/icons/chains/rsz_joc.jpg',
    gecko_id: 'japan-open-chain',
  },
  {
    caip: 'eip155:258432',
    namespace: 'eip155',
    chain_identifier: 258432,
    name: 'Althea L1 Mainnet',
    native_coin_id: 'ALTHEA',
    image: 'https://icons.llamao.fi/icons/chains/rsz_standx.jpg',
    gecko_id: 'althea',
  },
  {
    caip: 'eip155:97741',
    namespace: 'eip155',
    chain_identifier: 97741,
    name: 'Pepu',
    native_coin_id: 'PEPU',
    image: 'https://icons.llamao.fi/icons/chains/rsz_pepu.jpg',
    gecko_id: 'pepe-unchained-2',
  },
  {
    caip: 'eip155:1101',
    namespace: 'eip155',
    chain_identifier: 1101,
    name: 'Polygon zkEVM',
    native_coin_id: 'ETH',
    image: 'https://chain-icons.s3.amazonaws.com/chainlist/1101',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:7777777',
    namespace: 'eip155',
    chain_identifier: 7777777,
    name: 'Zora',
    native_coin_id: 'ETH',
    image: 'https://chain-icons.s3.amazonaws.com/zora',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:11155111',
    namespace: 'eip155',
    chain_identifier: 11155111,
    name: 'Sepolia',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/1/native.webp',
    gecko_id: null,
  },
  {
    caip: 'eip155:8453',
    namespace: 'eip155',
    chain_identifier: 8453,
    name: 'Base',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/8453/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:84532',
    namespace: 'eip155',
    chain_identifier: 84533,
    name: 'Base Sepolia',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/8453/native.webp',
    gecko_id: null,
  },
  {
    caip: 'eip155:130',
    namespace: 'eip155',
    chain_identifier: 130,
    name: 'Unichain',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/130/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'eip155:1868',
    namespace: 'eip155',
    chain_identifier: 1868,
    name: 'Soneium',
    native_coin_id: 'ETH',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/1868/native.webp',
    gecko_id: 'ethereum',
  },
  {
    caip: 'solana:mainnet',
    namespace: 'solana',
    chain_identifier: 0,
    name: 'Solana',
    native_coin_id: 'SOL',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/solana/native.webp',
    gecko_id: 'solana',
  },
  {
    caip: 'solana:devnet',
    namespace: 'solana',
    chain_identifier: 0,
    name: 'Solana Devnet',
    native_coin_id: 'SOL',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/solana/native.webp',
    gecko_id: null,
  },
  {
    caip: 'solana:testnet',
    namespace: 'solana',
    chain_identifier: 0,
    name: 'Solana Testnet',
    native_coin_id: 'SOL',
    image:
      'https://pub-c00e8ea6219e4be79477cc4888b05ffe.r2.dev/tokens/solana/native.webp',
    gecko_id: null,
  },
];

/**
 * Gets the chain registry entry by CAIP-style ID.
 * @param id The CAIP-style CAIP string (e.g., "eip155:1")
 * @returns The chain registry entry or null if not found
 */
export function getChainRegistryByCaip(id: string) {
  return CHAIN_REGISTRY.find((p) => p.caip === id) ?? null;
}

/**
 * Gets the chain registry entry by chain ID.
 * @param chainId The chain ID (e.g., "1")
 * @returns The chain registry entry or null if not found
 */
export function getChainRegistryByChainId(chainId: string) {
  return (
    CHAIN_REGISTRY.find((p) => p.chain_identifier === Number(chainId)) ?? null
  );
}
